# Storage classes for persistent data.
redisStorageClass: microk8s-hostpath
updateStorageClass: microk8s-hostpath
persistantStorageClass: microk8s-hostpath

# Overwrites storage size for update-directory volume. (default: 200Gi)
updateStorageSize: 20Gi

# CPU Revervation 
defaultReqCPU: "0m"
alerterReqCPU: "0m"
apmReqCPU: "0m"
dispatcherReqCPU: "0m"
elasticHelperReqCPU: "0m"
esMetricsReqCPU: "0m"
expiryReqCPU: "0m"
frontendReqCPU: "0m"
heartbeatReqCPU: "0m"
internalUIReqCPU: "0m"
ingestUIReqCPU: "0m"
ingesterReqCPU: "0m"
logstashReqCPU: "0m"
metricsReqCPU: "0m"
plumberReqCPU: "0m"
redisVolatileReqCPU: "0m"
redisPersistentReqCPU: "0m"
scalerReqCPU: "0m"
serviceServerReqCPU: "0m"
socketIOReqCPU: "0m"
statisticsReqCPU: "0m"
uiReqCPU: "0m"
updaterReqCPU: "0m"
workflowReqCPU: "0m"

# Many kubernetes environments don't provide multiple read multiple write volumes.
# We want to use them, but they don't have to be high performance. If this flag
# is true, assemblyline will launch NFS servers internally to get RWX volumes.
# Otherwise, the storage class for updateStorageClass needs to support RWX
internalNFS: false

# Internal configuration for assemblyline components. See the assemblyline
# administration documentation for more details.
# https://cybercentrecanada.github.io/assemblyline4_docs/
configuration:
  core:
    scaler:
      service_defaults:
        min_instances: 0
    services:
      cpu_reservation: 0
  ui:
    fqdn: "localhost"

# Configuration for the elasticsearch instance used for system data.
# Values an administrator is likely to want to change to scale their deployment are:
#     replicas
#     resources
#     volumeClaimTemplate
datastore:
  replicas: 1
  esJavaOpts: '-Xms2g -Xmx2g'
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi
  volumeClaimTemplate:
    storageClassName: microk8s-hostpath
    resources:
      requests:
        storage: 20Gi

# Configuration for the file storage
# Values an administrator is likely to want to change to scale their deployment are:
#     persistence
filestore:
  persistence:
    size: 20Gi
    StorageClass: microk8s-hostpath
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi

# When true, logging and metrics pods are launched to gather information about the 
# k8s cluster and its pods
loggingAndMetrics: false

# When true an elk stack is launched inside assemblyline to collect logs and metrics
# Otherwise, logstash is run, but no kibana or elasticsearch for logs
internalLogging: false

# Make sure we use the same datastore for logging if we turn it on
seperateInternalLogging: false
loggingHost: datastore-master:9200