apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-config
  labels:
    k8s-app: apm
data:
  apm.yml: |
    apm-server:
      host: "0.0.0.0:8200"
      kibana:
        enabled: true
        host: {{ .Values.loggingKibanaHost }}:5601
        path: {{ .Values.loggingKibanaPath }}
        protocol: http
        username: {{ .Values.loggingUsername }}
        password: {{ .Values.loggingPassword }}

    logging:
      level: warning
      json: true

    output.elasticsearch:
      hosts: ['{{ .Values.loggingHost }}']
      username: {{ .Values.loggingUsername }}
      password: {{ .Values.loggingPassword }}

    setup.template.settings.index:
      number_of_shards: 1
      number_of_replicas: 0
