dependencies:
  - name: assemblyline
    repository: file://../assemblyline
    version: 4.0.6
  - name: elasticsearch
    repository: https://helm.elastic.co/
    version: 7.7.0
    alias: log-storage
  - name: kibana
    repository: https://helm.elastic.co/
    version: 7.7.0
    alias: kibana