# The assemblyline config that will be projected into all the assemblyline pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-global-config
data:
  config: |
    core:
      alerter:
        delay: 0
      metrics:
        apm_server:
          server_url: http://{{ .Release.Name }}-apm:8200/
        elasticsearch:
          hosts: ["{{ .Release.Name }}-datastore"]
        kibana:
          host: {{ .Release.Name }}-kibana
        redis:
          host: {{ .Release.Name }}-redis-volatile
          port: 6379
      redis:
        nonpersistent:
          host: {{ .Release.Name }}-redis-volatile
          port: 6379
        persistent:
          host: {{ .Release.Name }}-redis-persistent
          port: 6379
    datastore:
      elasticsearch:
        nodes: [{{ .Release.Name }}-datastore:9200]
      hosts: [{{ .Release.Name }}-datastore:9200]
    filestore:
      cache: ["s3://al_storage_key:Ch@ngeTh!sPa33w0rd@{{ .Release.Name }}-filestore:9000?s3_bucket=al-cache&use_ssl=False"]
      storage: ["s3://al_storage_key:Ch@ngeTh!sPa33w0rd@{{ .Release.Name }}-filestore:9000?s3_bucket=al-storage&use_ssl=False"]
    logging:
      log_to_console: true
      log_to_file: false
      log_to_syslog: false
#      log_level: DEBUG
#    ui:
#      debug: true