# The assemblyline config that will be projected into all the assemblyline pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-global-config
data:
  config: |
    core:
      alerter:
        delay: 0
      metrics:
        apm_server:
          server_url: http://apm:8200/
        elasticsearch:
          hosts: ["datastore"]
        kibana:
          host: kibana
        redis:
          host: redis-volatile
          port: 6379
      redis:
        nonpersistent:
          host: redis-volatile
          port: 6379
        persistent:
          host: redis-persistent
          port: 6379
      scaler:
        core_namespace: {{ .Release.Name }}
        service_namespace: {{ template "service-namespace" . }}
    datastore:
      elasticsearch:
        nodes: [datastore:9200]
      hosts: [datastore:9200]
    filestore:
      cache: ["s3://al_storage_key:Ch@ngeTh!sPa33w0rd@filestore:9000?s3_bucket=al-cache&use_ssl=False"]
      storage: ["s3://al_storage_key:Ch@ngeTh!sPa33w0rd@filestore:9000?s3_bucket=al-storage&use_ssl=False"]
    logging:
      log_to_console: true
      log_to_file: false
      log_to_syslog: false
