apiVersion: v1
kind: Service
metadata:
  name: apm
  labels:
    app: assemblyline
    section: logging
    component: apm
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: logging
    component: apm
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200