{{ if .Values.enableAPM }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-config
  labels:
    k8s-app: apm
data:
  apm.yml: |
    apm-server:
      host: "0.0.0.0:8200"
      kibana:
        enabled: true
        host: {{ .Values.kibanaHost }}
        path:
        protocol: https
        username: ${LOGGING_USERNAME}
        password: ${LOGGING_PASSWORD}
        ssl:
          verification_mode: ${LOGGING_TLS_VERIFY}

    logging:
      level: warning
      json: true

    output.elasticsearch:
      hosts: ['${LOGGING_URL}']
      username: ${LOGGING_USERNAME}
      password: ${LOGGING_PASSWORD}
      ssl:
        verification_mode: ${LOGGING_TLS_VERIFY}

{{end}}