apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-config
  labels:
    k8s-app: apm
data:
  apm.yml: |
    apm-server:
      host: "0.0.0.0:8200"
      kibana:
        enabled: true
        host: kibana:5601
        path: kibana
        protocol: http
        username: elastic
        password: {{ .Values.loggingPassword }}

    logging:
      level: warning
      json: true

    output.elasticsearch:
      hosts: ['logging-datastore-master:9200']
      username: elastic
      password: {{ .Values.loggingPassword }}

    setup.template.settings.index:
      number_of_shards: 1
      number_of_replicas: 0
