apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ui-hpa
spec:
  maxReplicas: {{ .Values.APIInstancesMax }}
  minReplicas: {{ .Values.APIInstances }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui
  targetCPUUtilizationPercentage: 95 # target CPU utilization

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: internal-ui-hpa
spec:
  maxReplicas: {{ .Values.internalAPIInstancesMax }}
  minReplicas: {{ .Values.internalAPIInstances }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: internal-ui
  targetCPUUtilizationPercentage: 95 # target CPU utilization

{{ if .Values.separateIngestAPI }} 
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ui-ingest-hpa
spec:
  maxReplicas: {{ .Values.ingestAPIInstancesMax }}
  minReplicas: {{ .Values.ingestAPIInstances }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui-ingest
  targetCPUUtilizationPercentage: 95 # target CPU utilization

{{end}}
---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ingester-hpa
spec:
  maxReplicas: {{ .Values.ingesterInstancesMax }}
  minReplicas: {{ .Values.ingesterInstances }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingester
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 95 # target CPU utilization
  behavior:
    scaleUp:
      policies:
        - type: Percent
          value: 100
          periodSeconds: 300
      stabilizationWindowSeconds: 300

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dispatcher-hpa
spec:
  maxReplicas: {{ .Values.dispatcherInstancesMax }}
  minReplicas: {{ .Values.dispatcherInstances }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dispatcher
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 95 # target CPU utilization
  behavior:
    scaleUp:
      policies:
        - type: Percent
          value: 100
          periodSeconds: 600
      stabilizationWindowSeconds: 600

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-server-hpa
spec:
  maxReplicas: {{ .Values.serviceServerCountMax }}
  minReplicas: {{ .Values.serviceServerCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-server
  targetCPUUtilizationPercentage: 95 # target CPU utilization