# The assemblyline config that will be projected into all the assemblyline pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-global-config
data:
  config: |
    auth:
      internal:
        signup:
          enabled: false
          notify:
            base_url: https://api.notification.alpha.canada.ca
            api_key: stagingmlwrca-8d1dcea3-00ae-4e16-8550-5ae9bde4796e-347ac42d-fdac-4ac3-a86b-732f7c177258
            registration_template: 95f51ab4-5156-4e61-8205-2aced49f016e
            password_reset_template: a31a905d-df18-41b0-a155-114997ac66f6
          valid_email_patterns: [".*@cyber\\.gc\\.ca"]
      oauth:
        enabled: true
        providers:
          azure_ad:
            auto_create: true
            auto_sync: false
            client_id: 14b51979-1a72-4262-b552-85b05d81f3e8
            client_secret: "g1x:TT1]iFamiZYz[2P9lppMise.n4_v"
    core:
      alerter:
        delay: 0
      metrics:
        apm_server:
          server_url: http://apm:8200/
        elasticsearch:
          hosts: ["http://elastic:{{ .Values.loggingPassword }}@logging-datastore-master"]
        redis:
          host: redis-volatile
          port: 6379
      redis:
        nonpersistent:
          host: redis-volatile
          port: 6379
        persistent:
          host: redis-persistent
          port: 6379
      scaler:
        service_defaults:
          backlog: 10
          min_instances: 1
          growth: 60
          shrink: 20
          environment:
            - name: 'SERVICE_API_HOST'
              value: 'http://service-server.{{ $.Release.Name }}.svc.cluster.local:5003'
    datastore:
      hosts: ["http://elastic:{{ .Values.elasticPassword }}@datastore-master:9200"]
    filestore:
      cache: ["s3://{{ .Values.filestoreKey }}:{{ .Values.filestorePassword }}@filestore:9000?s3_bucket=al-cache&use_ssl=False"]
      storage: ["s3://{{ .Values.filestoreKey }}:{{ .Values.filestorePassword }}@filestore:9000?s3_bucket=al-storage&use_ssl=False"]
    logging:
      log_to_console: true
      log_to_file: false
      log_to_syslog: false
    ui:
      fqdn: {{ .Values.domain }}
      email: assemblyline@cyber.gc.ca
      tos_lockout: false
      tos: >
        ##This is a development system. Do not share any data found on this site. Do not trust the classification markings to be accurate.
  classification: |
    enforce: true
    groups:
    - aliases: []
      auto_select: true
      description: Employees of CSE
      name: CSE
      short_name: CSE
    levels:
    - aliases:
      - UNRESTRICTED
      css:
        banner: alert-default
        label: label-default
        text: text-muted
      description: Data is not classified
      lvl: 100
      name: UNCLASSIFIED
      short_name: U
    - aliases: []
      css:
        banner: alert-success
        label: label-success
        text: text-success
      description: Recipients may share TLP:GREEN information with peers and partner organizations
        within their sector or community, but not via publicly accessible channels. Information
        in this category can be circulated widely within a particular community. TLP:GREEN
        information may not be released outside of the community.
      lvl: 110
      name: TLP:GREEN
      short_name: TLP:G
    - aliases: []
      css:
        banner: alert-warning2
        label: label-warning
        text: text-warning2
      description: Recipients may only share TLP:AMBER information with members of their
        own organization and with clients or customers who need to know the information
        to protect themselves or prevent further harm.
      lvl: 120
      name: TLP:AMBER
      short_name: TLP:A
    required:
      - aliases: []
        description: Produced using a commercial tool with limited distribution
        name: COMMERCIAL
        short_name: CMR
    subgroups:
      - aliases: []
        description: Member of Incident Response team
        name: IR_TEAM
        short_name: IR
      - aliases: []
        description: Member of the Canadian Centre for Cyber Security
        require_group: CSE
        name: CCCS
        short_name: CCCS
      - aliases: []
        description: Member of the Beaver Team
        require_group: CSE
        name: BEAVER
        short_name: BVR
    restricted: TLP:A
    unrestricted: U