# The assemblyline config that will be projected into all the assemblyline pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-global-config
data:
  config: |
    core:
      alerter:
        delay: 0
      metrics:
        elasticsearch:
          hosts: ["http://{{ .Values.loggingUsername }}:{{ .Values.loggingPassword }}@{{ .Values.loggingHost }}"]
        redis:
          host: redis-volatile
          port: 6379
      redis:
        nonpersistent:
          host: redis-volatile
          port: 6379
        persistent:
          host: redis-persistent
          port: 6379
      scaler:
        service_defaults:
          backlog: 10
          min_instances: 1
          growth: 60
          shrink: 20
          environment:
            - name: 'SERVICE_API_HOST'
              value: 'http://service-server:5003'
    datastore:
      hosts: ["http://elastic:{{ .Values.elasticPassword }}@datastore-master:9200"]
    filestore:
      cache: ["s3://{{ .Values.filestoreKey }}:{{ .Values.filestorePassword }}@filestore:9000?s3_bucket=al-cache&use_ssl=False"]
      storage: ["s3://{{ .Values.filestoreKey }}:{{ .Values.filestorePassword }}@filestore:9000?s3_bucket=al-storage&use_ssl=False"]
    logging:
      log_to_console: true
      log_to_file: false
      log_to_syslog: false
    ui:
      fqdn: {{ .Values.domain }}
  classification: |
    enforce: true
    groups:
    - aliases: [DEPTS, ANY]
      description: Users of department 1.
      name: DEPARTMENT 1
      short_name: D1
      solitary_display_name: ANY
    - aliases: [DEPTS]
      description: Users of department 2.
      name: DEPARTMENT 2
      short_name: D2
    levels:
    - aliases: []
      css: {banner: alert-default, label: label-default, text: text-muted}
      description: No restrictions applied to data.
      lvl: 100
      name: UNRESTRICTED
      short_name: U
    - aliases: [CLASSIFIED, DO NOT LOOK]
      css: {banner: alert-info, label: label-primary, text: text-primary}
      description: Data restricted to a certain few...
      lvl: 200
      name: RESTRICTED
      short_name: R
    required:
    - aliases: []
      description: Gotta be a super user to see this!
      name: SUPER USER
      require_lvl: 200
      short_name: SU
    - aliases: [GOD]
      description: Gotta be an administrator to see this!
      name: ADMIN
      short_name: ADM
    restricted: R//GOD//ANY
    subgroups:
    - aliases: []
      description: Users of group 1 (which are part of deparment 1).
      limited_to_group: D1
      name: GROUP 1
      require_group: D1
      short_name: G1
    - aliases: []
      description: Users of group 2 (can be part of any department).
      name: GROUP 2
      short_name: G2
    unrestricted: U