---
apiVersion: v1
kind: Service
metadata:
  name: datastore
  labels:
    app: assemblyline
    section: core
    component: datastore
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: datastore
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datastore
spec:
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: datastore
  serviceName: datastore
  replicas: 1
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: datastore
    spec:
      terminationGracePeriodSeconds: 60
      priorityClassName: al-infra
      containers:
      - name: elasticsearch
        env:
        - name: ES_JAVA_OPTS
          value: '-Xms512m -Xmx512m'
        - name: DISCOVERY_TYPE
          value: 'single-node'
        image: sgaroncse/elasticsearch:7.3.0
        livenessProbe:
          httpGet:
            path: _cluster/health
            port: 9200
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 3
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: datastore-data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: datastore-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.datastore }}
      resources:
        requests:
          storage: 50Gi
