apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-dispatcher-submissions
  labels:
    app: assemblyline
    component: disptacher-submissions
spec:
  containers:
    - name: al-dispatch-submissions
      image: cccs/assemblyline-core:{{ .Values.coreVersion }}
      imagePullPolicy: Always
      command: ['python3', '-m', 'al_core.dispatching.run_submissions']
      volumeMounts:
        - name: al-config
          mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dispatcher-submissions
spec:
  clusterIP: None  # AL services are headless, and communicate through redis
  selector:
    app: assemblyline
    component: disptacher-submissions
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-dispatcher-files
  labels:
    app: assemblyline
    component: disptacher-files
spec:
  containers:
    - name: al-dispatch-files
      image: cccs/assemblyline-core:{{ .Values.coreVersion }}
      imagePullPolicy: Always
      command: ['python3', '-m', 'al_core.dispatching.run_files']
      volumeMounts:
        - name: al-config
          mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dispatcher-files
spec:
  clusterIP: None  # AL services are headless, and communicate through redis
  selector:
    app: assemblyline
    component: disptacher-files
