---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-expiry
  labels:
    app: assemblyline-{{ .Release.Name }}
    section: core
    component: expiry
spec:
  containers:
    - name: al-expiry
      image: cccs/assemblyline-core:{{ .Values.coreVersion }}
      imagePullPolicy: Always
      command: ['python', '-m', 'al_core.expiry.run_expiry']
      volumeMounts:
        - name: al-config
          mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-expiry
spec:
  clusterIP: None  # AL services are headless, and communicate through redis
  selector:
    app: assemblyline
    section: core
    component: expiry
