apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-ingester-ingest
  labels:
    app: assemblyline
    component: ingester-ingest
spec:
  containers:
    - name: al-ingester-ingest
      image: cccs/assemblyline-core:{{ .Values.coreVersion }}
      command: ['python3', '-m', 'al_core.ingester.run_ingest']
      volumeMounts:
        - name: al-config
          mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingester-ingest
spec:
  clusterIP: None  # AL services are headless, and communicate through redis
  selector:
    app: assemblyline
    component: ingester-ingest
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-ingester-internal
  labels:
    app: assemblyline
    component: ingester-internal
spec:
  containers:
    - name: al-ingester-internal
      image: cccs/assemblyline-core:{{ .Values.coreVersion }}
      command: ['python', '-m', 'al_core.ingester.run_internal']
      volumeMounts:
        - name: al-config
          mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingester-internal
spec:
  clusterIP: None  # AL services are headless, and communicate through redis
  selector:
    app: assemblyline
    component: ingester-internal
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-ingester-submit
  labels:
    app: assemblyline
    component: ingester-submit
spec:
  containers:
    - name: al-ingester-submit
      image: cccs/assemblyline-core:{{ .Values.coreVersion }}
      command: ['python', '-m', 'al_core.ingester.run_submit']
      volumeMounts:
        - name: al-config
          mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingester-submit
spec:
  clusterIP: None  # AL services are headless, and communicate through redis
  selector:
    app: assemblyline
    component: ingester-submit
