{{- if not .Values.tlsSecretName }}
#  {{ $ca := genCA "svc-cat-ca" 3650 }}
#  {{ $cn := .Values.domain }}
  {{ $server := genSelfSignedCert .Values.configuration.ui.fqdn nil nil 365 }}

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-generated-cert
  labels:
    app: assembyline
data:
  tls.crt: {{ b64enc $server.Cert }}
  tls.key: {{ b64enc $server.Key }}
{{ end }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{- range $key, $value := .Values.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
    - hosts: [{{ .Values.configuration.ui.fqdn }}]
      secretName: {{ if .Values.tlsSecretName }} {{.Values.tlsSecretName }} {{else}} {{ .Release.Name }}-generated-cert {{end}}
  rules:
    - host: {{ if .Values.ingressHost }} {{.Values.ingressHost }} {{else}} {{ .Values.configuration.ui.fqdn }} {{end}}
      http:
        paths:
          - path: /socket.io/
            backend:
              serviceName: socketio
              servicePort: 5002
          - path: /
            backend:
              serviceName: ui
              servicePort: 5000
          {{ if .Values.internalLogging }}
          - path: /kibana/
            backend:
              serviceName: kibana
              servicePort: 5601
          {{ end }}
