{{- if not .Values.tls.secretName }}
  {{ $ca := genCA "svc-cat-ca" 3650 }}
  {{ $cn := .Values.net.domain }}
  {{ $server := genSignedCert $cn nil nil 365 $ca }}
  {{ $client := genSignedCert "" nil nil 365 $ca }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-generated-cert
  labels:
    app: assembyline
data:
#  caCert: {{ b64enc $ca.Cert }}
#  clientCert: {{ b64enc $client.Key }}
#  clientKey: {{ b64enc $client.Cert }}
  cert: {{ b64enc $server.Cert }}
  key: {{ b64enc $server.Key }}
{{ end }}
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: {{ .Release.Name }}-nginx
#  labels:
#    app: assemblyline
#    component: nginx
#spec:
#  containers:
#  - name: nginx
#    image: nginx:1.15.10
#    volumeMounts:
#    - name: nginx-conf
#      mountPath: /etc/nginx/conf.d/
#    - name: cert-conf
#      mountPath: /etc/ssl/
#  volumes:
#    - name: nginx-conf
#      configMap:
#        name: {{ .Release.Name }}-global-config
#        items:
#          - key: http_redirect.conf
#            path: http_redirect.conf
#          - key: nginx.conf
#            path: default.conf
#    - name: cert-conf
#      secret:
#        secretName: {{ if .Values.tls.secretName }} {{.Values.tls.secretName}} {{else}} {{ .Release.Name }}-generated-cert {{end}}
#        items:
#          - key: serverCert
#            path: nginx.crt
#          - key: serverKey
#            path: nginx.key
#---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
#  namespace:
spec:
  tls:
    - hosts:
      secretName: {{ if .Values.tls.secretName }} {{.Values.tls.secretName}} {{else}} {{ .Release.Name }}-generated-cert {{end}}
  rules:
    - http:
        paths:
          - path: /socket.io/
            backend:
              serviceName: {{ .Release.Name }}-socketio
              servicePort: 5002
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-ui
              servicePort: 5000
