# Generate self-signed certificate
{{- if not .Values.tlsSecretName }}
{{ $server := genSelfSignedCert .Values.configuration.ui.fqdn nil (list .Values.configuration.ui.fqdn) 365 }}

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-generated-cert
  labels:
    app: assemblyline
data:
  tls.crt: {{ b64enc $server.Cert }}
  tls.key: {{ b64enc $server.Key }}
{{- end }}

---

# FRONTEND INGRESS (External)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  annotations:
    {{- range $key, $value := .Values.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    appgw.ingress.kubernetes.io/backend-hostname: "frontend"
spec:
  tls:
    - hosts: [{{ .Values.configuration.ui.fqdn }}]
      secretName: {{ if .Values.tlsSecretName }} {{.Values.tlsSecretName }} {{else}} {{ .Release.Name }}-generated-cert {{end}}
  rules:
    - host: {{ .Values.configuration.ui.fqdn | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000

---

# SOCKETIO INGRESS (Internal)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-socketio-ingress
  annotations:
    {{- range $key, $value := .Values.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    appgw.ingress.kubernetes.io/backend-hostname: "socketio"
spec:
  tls:
    - hosts: [{{ .Values.configuration.ui.fqdn }}]
      secretName: {{ if .Values.tlsSecretName }} {{.Values.tlsSecretName }} {{else}} {{ .Release.Name }}-generated-cert {{end}}
  rules:
    - host: {{ .Values.configuration.ui.fqdn | quote }}
      http:
        paths:
          - path: /socket.io/
            pathType: Prefix
            backend:
              service:
                name: socketio
                port:
                  number: 5002

---

# UI INGRESS (Internal)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ui-ingress
  annotations:
    {{- range $key, $value := .Values.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    appgw.ingress.kubernetes.io/backend-hostname: "ui"
spec:
  tls:
    - hosts: [{{ .Values.configuration.ui.fqdn }}]
      secretName: {{ if .Values.tlsSecretName }} {{.Values.tlsSecretName }} {{else}} {{ .Release.Name }}-generated-cert {{end}}
  rules:
    - host: {{ .Values.configuration.ui.fqdn | quote }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 5000

---

# UI-INGEST INGRESS (Internal)
{{ if .Values.separateIngestAPI }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ui-ingest-ingress
  annotations:
    {{- range $key, $value := .Values.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    appgw.ingress.kubernetes.io/backend-hostname: "ui"
spec:
  tls:
    - hosts: [{{ .Values.configuration.ui.fqdn }}]
      secretName: {{ if .Values.tlsSecretName }} {{.Values.tlsSecretName }} {{else}} {{ .Release.Name }}-generated-cert {{end}}
  rules:
    - host: {{ .Values.configuration.ui.fqdn | quote }}
      http:
        paths:
          - path: /api/v4/ingest/
            pathType: Prefix
            backend:
              service:
                name: ui-ingest
                port:
                  number: 5000
{{end}}

---
{{ if .Values.ingressPaths }}
{{ .Values.ingressPaths | toYaml | indent 10 }}
{{ end }}
