{{- if not .Values.tls.secretName }}
  {{ $ca := genCA "svc-cat-ca" 3650 }}
  {{ $cn := .Values.net.domain }}
  {{ $server := genSignedCert $cn nil nil 365 $ca }}
  {{ $client := genSignedCert "" nil nil 365 $ca }}

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-generated-cert
  labels:
    app: assembyline
data:
  tls.crt: {{ b64enc $server.Cert }}
  tls.key: {{ b64enc $server.Key }}
{{ end }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
#  namespace:
spec:
  tls:
    - hosts:
      secretName: {{ if .Values.tls.secretName }} {{.Values.tls.secretName}} {{else}} {{ .Release.Name }}-generated-cert {{end}}
  rules:
    - http:
        paths:
          - path: /socket.io/
            backend:
              serviceName: {{ .Release.Name }}-socketio
              servicePort: 5002
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-ui
              servicePort: 5000
          - path: /kibana/
            backend:
              serviceName: {{ .Release.Name }}-kibana
              servicePort: 5601