apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: assemblyline
    section: core
    component: kibana
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: kibana
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: assemblyline
    section: core
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: kibana
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: kibana
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.3.0
          imagePullPolicy: Always
          env:
          - name: SERVER_NAME
            value: localhost
          - name: ELASTICSEARCH_HOSTS
            value: http://datastore:9200
          - name: SERVER_BASEPATH
            value: /kibana
          - name: SERVER_REWRITEBASEPATH
            value: "true"
          ports:
          - containerPort: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm
  labels:
    app: assemblyline
    section: core
    component: apm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: apm
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: apm
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: apm
          image: sgaroncse/apm-server:7.3.0
          imagePullPolicy: Always
          env:
          - name: ES_HOSTS
            value: datastore:9200
          ports:
          - containerPort: 8200

