apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: assemblyline
    section: core
    component: kibana
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: kibana
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: assemblyline
    section: core
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: kibana
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: kibana
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.4.0
          imagePullPolicy: Always
          env:
          - name: SERVER_NAME
            value: localhost
          - name: ELASTICSEARCH_HOSTS
            value: http://logging-datastore:9200
          - name: ELASTICSEARCH_USERNAME
            value: kibana
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: datastore-passwords
                key: kibana
          - name: SERVER_BASEPATH
            value: /kibana
          - name: SERVER_REWRITEBASEPATH
            value: "true"
          ports:
          - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: apm
  labels:
    app: assemblyline
    section: core
    component: apm
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: apm
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm
  labels:
    app: assemblyline
    section: core
    component: apm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: apm
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: apm
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: apm
          image: sgaroncse/apm-server:7.4.0
          imagePullPolicy: Always
          env:
          - name: ES_HOSTS
            value: logging-datastore:9200
          - name: ELASTICSEARCH_USERNAME
            value: apm
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: datastore-passwords
                key: apm
          command: ["/bin/bash", "-c", "/usr/local/bin/docker-entrypoint -e -E output.elasticsearch.username=$$ELASTICSEARCH_USERNAME -E output.elasticsearch.password=$$ELASTICSEARCH_PASSWORD"]
          ports:
          - containerPort: 8200

