{{ if ne .Release.Name .Release.Namespace }}
  {{ fail "An Assemblyline release name must match it's namespace." }}
{{ end }}

# As long as the above condition is true, we don't need to explicitly create this namespace
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: {{ .Release.Name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "service-namespace" . }}