# Allow all core pods to talk to other pods
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-between-core
  labels:
    app: assemblyline
spec:
  podSelector:
    matchLabels:
      section: core
  ingress:
  - from:
    - podSelector:
        matchLabels:
          section: core
  egress:
  - to:
    - podSelector:
        matchLabels:
          section: core
---
# Allow pods to access DNS
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  labels:
    app: assemblyline
spec:
  # For all pods in the given namespace
  podSelector:
    matchLabels:
  # Allow egress to the dns service in the system namespace
  egress:
  - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
#  - to:  # It would be better to use this more specific selection, but its not broadly supported
#    - namespaceSelector:
#        matchLabels:
#          name: kube-system
#      podSelector:
#        matchLabels:
#          k8s-app: kube-dns
---
# Allow all ingress traffic to UI/socket-io/service-api
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-into-endpoints
spec:
  # For the matched services
  podSelector:
    matchLabels:
      app: assemblyline
      section: core
    matchExpressions:
    - key: component
      operator: In
      values: [ui, socketio, service-server]
  # Allow ingress from all sources, regardless of origin
  ingress:
  - from: []
---
# services to contact the service-server
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-service-api
spec:
  # For all pods in the service namespace
  podSelector:
    matchLabels:
      app: assemblyline
      section: service
  # Allow traffic to
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: assemblyline
          section: core
          component: service-server
---
# Let the scaler do whatever it wants
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-scaler
  labels:
    app: assemblyline
spec:
  # For the scaler
  podSelector:
    matchLabels:
      app: assemblyline
      section: core
      component: scaler
  # Allow egress to whatever
  egress:
  - to: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-state-metrics
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  egress:
  - to: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-metricbeat-daemon
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-metricbeat-metrics
  egress:
  - to: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-metricbeat-to-core
  labels:
    app: assemblyline
spec:
  podSelector:
    matchLabels:
      section: core
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-metricbeat-metrics
