# Create a POD/Service for non-persisted redis
apiVersion: v1
kind: Pod
metadata:
  name: redis-volatile
  labels:
    app: assemblyline
    section: core
    component: redis-volatile
spec:
  containers:
  - name: redis
    image: redis
    ports:
      - containerPort: 6379
  priorityClassName: data-layer
---
apiVersion: v1
kind: Service
metadata:
  name: redis-volatile
  labels:
    app: assemblyline
    section: core
    component: redis-volatile
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: redis-volatile
  ports:
  - protocol: TCP
    port: 6379
---
# Create a StatefulSet/Service for persistent redis
apiVersion: v1
kind: Service
metadata:
  name: redis-persistent
  labels:
    app: assemblyline
    section: core
    component: redis-persistent
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: redis-persistent
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-persistent
spec:
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: redis-persistent
  serviceName: redis-persistent
  replicas: 1
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: redis-persistent
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        command: ['redis-server']
        args: ['--appendonly', 'yes', '--auto-aof-rewrite-percentage', '0']
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /var/opt/redislabs/
      priorityClassName: data-layer
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.redis }}
      resources:
        requests:
          storage: 20Gi
