apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: assemblyline
    component: redis
spec:
  containers:
  - name: redis
    image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-volatile
spec:
  selector:
    app: assemblyline
    component: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379