apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler
  labels:
    app: assemblyline
    section: core
    component: scaler
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionCount }}
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: scaler
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: scaler
    spec:
      serviceAccountName: {{ .Release.Name }}-scaling-manager
      priorityClassName: al-core-priority
      containers:
        - name: scaler
          image: {{ .Values.assemblylineCoreImage }}:{{ .Values.coreVersion }}
          imagePullPolicy: Always
          {{ if .Values.enableCoreDebugging}}
          command: ['python', '-m', 'debugpy', '--listen', 'localhost:5678', '-m', 'assemblyline_core.scaler.run_scaler']
          {{ else }}
          command: ['python', '-m', 'assemblyline_core.scaler.run_scaler']
          {{ end}}
          volumeMounts:
          {{ include "assemblyline.coreMounts" . | indent 12 }}
            - name: update-directory
              mountPath: /mount/update_root/
          env:
          {{ include "assemblyline.coreEnv" . | indent 12 }}
            - name: KUBERNETES_AL_CONFIG
              value: {{ .Release.Name }}-global-config
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FILE_UPDATE_VOLUME
              value: update-directory
            - name: FILE_UPDATE_DIRECTORY
              value: /mount/update_root/
            - name: UI_SERVER
              value: http://internal-ui:5000
            - name: SERVICE_API_HOST
              value: http://service-server:5003              
            - name: CONFIGURATION_CONFIGMAP
              value: {{ .Release.Name }}-global-config
          resources:
            limits:
              cpu: "2"
              {{ if .Values.namespaceResourceLimited }}
              memory: 4Gi
              {{ end }}
            requests:
              cpu: {{ .Values.scalerReqCPU }}
              memory: 512Mi
#          livenessProbe:
#            exec:
#              command: [ "bash", "-c", "if [[ ! `find /tmp/heartbeat -newermt '-30 seconds'` ]]; then false; fi" ]
#            initialDelaySeconds: 30
#            periodSeconds: 30
      volumes:
      {{ include "assemblyline.coreVolumes" . | indent 8 }}
        - name: update-directory
          persistentVolumeClaim:
            claimName: update-directory
