{{ if .Values.internalFilestore }}
{{ if not (lookup "v1" "Secret" .Release.Namespace "internal-filestore-keys") }}
apiVersion: v1
kind: Secret
metadata:
  name: internal-filestore-keys
type: Opaque
stringData:
  accesskey: {{ randAlphaNum 16 }}
  secretkey: {{ randAlphaNum 16 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-helper-secret
data:
  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  password:  {{ index (lookup "v1" "Secret" .Release.Namespace "elastic-helper-secret" | default (dict "data" (dict "password" (randAlphaNum 20 | b64enc)))).data "password" }}
  {{ end }}