{{- if .Values.tlsSecretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.tlsSecretProvider.className | default "assemblyline-secrets-provider" }}
spec:
  provider: {{ .Values.tlsSecretProvider.provider }}
  secretObjects:
  - secretName: {{ .Values.tlsSecretProvider.tlsSecretName | default "assemblyline-tls" }}
    type: kubernetes.io/tls
    data:
      - objectName: {{ .Values.tlsSecretProvider.tlsObjectName | default "assemblyline-tls-certificate" }}
        key: tls.crt
      - objectName: {{ .Values.tlsSecretProvider.tlsObjectName | default "assemblyline-tls-certificate" }}
        key: tls.key
  parameters:
  {{- toYaml $.Values.tlsSecretProvider.parameters | nindent 4 }}
    objects: |
      array:
        - |
          objectName: {{ .Values.tlsSecretProvider.tlsObjectName | default "assemblyline-tls-certificate" }}
          objectType: secret
{{- end }}