{{ if .Values.internalFilestore }}
{{ if not (lookup "v1" "Secret" .Release.Namespace "internal-filestore-keys") }}
apiVersion: v1
kind: Secret
metadata:
  name: internal-filestore-keys
type: Opaque
stringData:
  accesskey: {{ randAlphaNum 16 }}
  secretkey: {{ randAlphaNum 16 }}
{{ end }}
{{ end }}