apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-scaling-manager
  labels:
    app: assemblyline
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-scaling-manager
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-scaling-manager
  namespace: {{ .Release.Name }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name:  {{ template "service-namespace" . }}-scaling-manager
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-scaling-manager
  namespace: {{ template "service-namespace" . }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
