apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-server
  labels:
    app: assemblyline
    section: core
    component: service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: service-server
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: service-server
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: service-server
          image: cccs/assemblyline-service-server:{{ .Values.sapiVersion }}
          command: ["python", "-m", "assemblyline_service_server.app"]
          imagePullPolicy: Always
          volumeMounts:
            - name: al-config
              mountPath: /etc/assemblyline/
          ports:
            - containerPort: 5003
      volumes:
        - name: al-config
          configMap:
            name: {{ .Release.Name }}-global-config
            items:
              - key: config
                path: config.yml
