apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-server
  labels:
    app: assemblyline
    section: core
    component: service-server
spec:
  replicas: {{ .Values.serviceServerInstances }}
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: service-server
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: service-server
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: service-server
          image: {{ .Values.assemblylineServiceAPIImage }}:{{ .Values.sapiVersion }}
          imagePullPolicy: Always
          volumeMounts:
          {{ include "assemblyline.coreMounts" . | indent 12 }}
          ports:
            - containerPort: 5003
          env:
          {{ include "assemblyline.coreEnv" . | indent 12 }}
            - name: WORKERS
              value: '2'
          resources:
            limits:
              cpu: 1
            requests:
              cpu: {{ .Values.serviceServerReqCPU }}
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 5003
          startupProbe:
            httpGet:
              path: /healthz/ready
              port: 5003
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 5003
      volumes:
      {{ include "assemblyline.coreVolumes" . | indent 8 }}
