apiVersion: v1
kind: Service
metadata:
  name: service-server
  labels:
    app: assemblyline
    section: core
    component: service-server
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: service-server
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
#kind: Service
#apiVersion: v1
#metadata:
#  name: service-server
#  labels:
#    app: assemblyline
#    section: core
#    component: service-server
#spec:
#  type: ExternalName
#  externalName: service-x.namespace-b.svc.cluster.local
#  ports:
#  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-server
  labels:
    app: assemblyline
    section: core
    component: service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: service-server
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: service-server
    spec:
      containers:
        - name: service-server
          image: cccs/assemblyline-service-server:{{ .Values.sapiVersion }}
          command: ["python", "-m", "al_service_server.app"]
          imagePullPolicy: Always
          volumeMounts:
            - name: al-config
              mountPath: /etc/assemblyline/
          ports:
            - containerPort: 5003
      volumes:
        - name: al-config
          configMap:
            name: {{ .Release.Name }}-global-config
            items:
              - key: config
                path: config.yml
