apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-scaling-manager
  labels:
    app: assemblyline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-node-viewer
rules:
- apiGroups: [""]
  resources: ["nodes", "resourcequotas"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-job-viewer
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-event-viewer
rules:
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-scaling-manager
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-scaling-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-scaling-manager-nodes
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-scaling-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-node-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-scaling-manager-events
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-scaling-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-event-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-scaling-manager-jobs
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-scaling-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-job-viewer
  apiGroup: rbac.authorization.k8s.io
---
