apiVersion: v1
kind: Pod
metadata:
  name: ui
  labels:
    app: assemblyline
    section: core
    component: ui
spec:
  containers:
  - name: ui
    image: cccs/assemblyline-ui:{{ .Values.uiVersion }}
    volumeMounts:
      - name: al-config
        mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: assemblyline
    section: core
    component: ui
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: ui
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: socketio
  labels:
    app: assemblyline
    section: core
    component: socketio
spec:
  containers:
  - name: socketio
    image: cccs/assemblyline-socketio:{{ .Values.uiVersion }}
#    command: ["python"]
#    args: ["-m", "al_ui.socketsrv"]
    ports:
      - containerPort: 5002
    volumeMounts:
      - name: al-config
        mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: socketio
  labels:
    app: assemblyline
    section: core
    component: socketio
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: socketio
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
