apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: assemblyline-{{ .Release.Name }}
    section: core
    component: ui
spec:
  containers:
  - name: ui
    image: cccs/assemblyline-ui:{{ .Values.uiVersion }}
    volumeMounts:
      - name: al-config
        mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
spec:
  selector:
    app: assemblyline-{{ .Release.Name }}
    section: core
    component: ui
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-socketio
  labels:
    app: assemblyline-{{ .Release.Name }}
    section: core
    component: socketio
spec:
  containers:
  - name: socketio
    image: cccs/assemblyline-socketio:{{ .Values.uiVersion }}
    volumeMounts:
      - name: al-config
        mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-socketio
spec:
  selector:
    app: assemblyline-{{ .Release.Name }}
    section: core
    component: socketio
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
---  # Allow UI/socketio to accept connections from anywhere
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name}}-allow-ui
spec:
  podSelector:
    matchLabels:
      app: assemblyline-{{ .Release.Name }}
      section: core
    matchExpressions:
    - key: component
      operator: In
      values: [ui, socketio]
  ingress:
  - {}