apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: assemblyline-{{ .Release.Name }}
    component: ui
    accessCore: "true"
spec:
  containers:
  - name: ui
    image: cccs/assemblyline-ui:{{ .Values.uiVersion }}
    volumeMounts:
      - name: al-config
        mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
spec:
  selector:
    app: assemblyline-{{ .Release.Name }}
    component: ui
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-socketio
  labels:
    app: assemblyline-{{ .Release.Name }}
    component: socketio
    accessCore: "true"
spec:
  containers:
  - name: socketio
    image: cccs/assemblyline-socketio:{{ .Values.uiVersion }}
    volumeMounts:
      - name: al-config
        mountPath: /etc/assemblyline/
  volumes:
    - name: al-config
      configMap:
        name: {{ .Release.Name }}-global-config
        items:
          - key: config
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-socketio
spec:
  selector:
    app: assemblyline-{{ .Release.Name }}
    component: socketio
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
