---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: assemblyline
    section: core
    component: ui
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: ui
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: assemblyline
    section: core
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: ui
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: ui
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: ui
          image: cccs/assemblyline-ui:{{ .Values.uiVersion }}
          imagePullPolicy: Always
          volumeMounts:
            - name: al-config
              mountPath: /etc/assemblyline/
          ports:
            - containerPort: 5000
      volumes:
        - name: al-config
          configMap:
            name: {{ .Release.Name }}-global-config
            items:
              - key: config
                path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: socketio
  labels:
    app: assemblyline
    section: core
    component: socketio
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: socketio
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio
  labels:
    app: assemblyline
    section: core
    component: socketio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: socketio
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: socketio
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: socketio
          image: cccs/assemblyline-socketio:{{ .Values.uiVersion }}
          imagePullPolicy: Always
          volumeMounts:
            - name: al-config
              mountPath: /etc/assemblyline/
          ports:
            - containerPort: 5002
      volumes:
        - name: al-config
          configMap:
            name: {{ .Release.Name }}-global-config
            items:
              - key: config
                path: config.yml
