---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: assemblyline
    section: core
    component: ui
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: ui
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: assemblyline
    section: core
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: ui
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: ui
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: ui
          image: cccs/assemblyline-ui:{{ .Values.uiVersion }}
          imagePullPolicy: Always
          volumeMounts:
            - name: al-config
              mountPath: /etc/assemblyline/
          ports:
            - containerPort: 5000
          command: ["gunicorn"]
          args: ["--config=/usr/local/lib/python3.7/site-packages/assemblyline_ui/gunicorn_config.py", "assemblyline_ui.app:app"]
      volumes:
        - name: al-config
          configMap:
            name: {{ .Release.Name }}-global-config
            items:
              - key: config
                path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: internal-ui
  labels:
    app: assemblyline
    section: core
    component: internal-ui
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: internal-ui
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-ui
  labels:
    app: assemblyline
    section: core
    component: internal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: internal-ui
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: internal-ui
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: internal-ui
          image: cccs/assemblyline-ui:{{ .Values.uiVersion }}
          env:
            - name: AL_UNSECURED_UI
              value: "true"
          imagePullPolicy: Always
          volumeMounts:
            - name: al-config
              mountPath: /etc/assemblyline/
            - name: ssl-certs
              mountPath: "/etc/internal-ssl/"
              readOnly: true
          ports:
            - containerPort: 5000
          command: ["gunicorn"]
          args: ["--config=/usr/local/lib/python3.7/site-packages/assemblyline_ui/gunicorn_config.py",  "--log-level=debug", "assemblyline_ui.app:app"]
          #"--keyfile=/etc/internal-ssl/tls.key", "--certfile=/etc/internal-ssl/tls.crt",
      volumes:
        - name: al-config
          configMap:
            name: {{ .Release.Name }}-global-config
            items:
              - key: config
                path: config.yml
        - name: ssl-certs
          secret:
            secretName: ui-internal-generated-cert
---
apiVersion: v1
kind: Service
metadata:
  name: socketio
  labels:
    app: assemblyline
    section: core
    component: socketio
spec:
  clusterIP: None
  selector:
    app: assemblyline
    section: core
    component: socketio
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio
  labels:
    app: assemblyline
    section: core
    component: socketio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: socketio
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: socketio
    spec:
      priorityClassName: al-core-priority
      containers:
        - name: socketio
          image: cccs/assemblyline-socketio:{{ .Values.uiVersion }}
          imagePullPolicy: Always
          volumeMounts:
            - name: al-config
              mountPath: /etc/assemblyline/
          ports:
            - containerPort: 5002
      volumes:
        - name: al-config
          configMap:
            name: {{ .Release.Name }}-global-config
            items:
              - key: config
                path: config.yml
