apiVersion: apps/v1
kind: Deployment
metadata:
  name: updater
  labels:
    app: assemblyline
    section: core
    component: updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: updater
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: updater
    spec:
      serviceAccountName: {{ .Release.Name }}-scaling-manager
      priorityClassName: al-core-priority
      containers:
        - name: updater
          image: cccs/assemblyline-core:{{ .Values.coreVersion }}
          imagePullPolicy: Always
          command: ['python', '-m', 'assemblyline_core.updater.run_updater']
          volumeMounts:
            - name: al-config
              mountPath: /etc/assemblyline/
            - name: update-directory
              mountPath: /mount/update_root/
          env:
            - name: KUBERNETES_AL_CONFIG
              value: {{ .Release.Name }}-global-config
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FILE_UPDATE_VOLUME
              value: update-directory
            - name: FILE_UPDATE_DIRECTORY
              value: /mount/update_root/
            - name: UI_SERVER
              value: http://internal-ui:5000
      volumes:
        - name: al-config
          configMap:
            name: {{ .Release.Name }}-global-config
            items:
              - key: config
                path: config.yml
              - key: classification
                path: classification.yml
              - key: tag_whitelist
                path: tag_whitelist.yml
        - name: update-directory
          persistentVolumeClaim:
            claimName: update-directory

