dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co/
    version: 7.6.0
    alias: datastore
  - name: elasticsearch
    repository: https://helm.elastic.co/
    version: 7.6.0
    alias: logging-datastore
  - name: minio
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 2.5.18
    alias: filestore
  - name: filebeat
    repository: https://helm.elastic.co/
    version: 7.6.0
    alias: filebeat
  - name: metricbeat
    repository: https://helm.elastic.co/
    version: 7.6.0
    alias: metricbeat
  - name: kibana
    repository: https://helm.elastic.co/
    version: 7.6.0
    alias: kibana
