# If you change the elasticsearch version, remember to also change the version at:
#   - values.yaml: the init container image tag
dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co/
    version: 7.6.0
    alias: datastore
  - name: filebeat
    repository: https://helm.elastic.co/
    version: 7.6.0
    alias: filebeat
  - name: metricbeat
    repository: https://helm.elastic.co/
    version: 7.6.0
    alias: metricbeat
