dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co/
    version: 7.5.1
    alias: datastore
  - name: minio
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 2.5.18
    alias: filestore
  - name: filebeat
    repository: https://helm.elastic.co/
    version: 7.5.1
    alias: filebeat
  - name: metricbeat
    repository: https://helm.elastic.co/
    version: 7.5.1
    alias: metricbeat
