# Default values for assemblyline.

coreVersion: '4.0.0.dev19'
uiVersion:   '4.0.0.dev26'
sapiVersion:   '4.0.0.dev6'

storage:
  filestore: default
  datastore: default
  redis: default

domain: localhost
maxBodySize: 100M

tls:
  secretName: ''

autoInstallServices:
  - apkaye
  - cleaver
  - espresso
  - extract
  - frankenstrings
  - iparse
  - metapeek
  - pdfid
  - peepdf
  - unpacker

serviceNamespace: null  # Will be {{ .Release.Name }}-services if not defined