# Default values for assemblyline.

coreVersion: '4.0.0.dev134'
uiVersion:   '4.0.0.dev90'
sapiVersion:   '4.0.0.dev61'

storage:
  filestore: default
  redis: default

domain: localhost
maxBodySize: 100M

tlsSecretName: ''

autoInstallServices:
  - apkaye
  - metapeek
  - metadefender
  - characterize
  - extract
  - virustotal-dynamic
  - virustotal-static

autoInstallLegacyServices:
  - pdfid
  - peepdf
  - unpacker
  - cleaver
  - espresso
  - frankenstrings
  - iparse
  - pefile
  - pixaxe
  - swiffer
  - torrentslicer
  - yara


serviceNamespace: null  # Will be {{ .Release.Name }}-services if not defined



elasticPassword: "Ch@ngeTh!sPa33w0rd"
loggingPassword: "Ch@ngeTh!sPa33w0rd"
notebookPassword: "Ch@ngeTh!sPa33w0rd"
filestorePassword: "Ch@ngeTh!sPa33w0rd"  # URL encoded version of the secretKey in the block below

filestore:
  fullnameOverride: "filestore"
  replicas: 1
  accessKey: "al_filestore"
  secretKey: "Ch@ngeTh!sPa33w0rd"
  priorityClassName: 'al-infra'


datastore:
  clusterName: "datastore"
  replicas: 3
  extraEnvs:
    - name: ELASTIC_USERNAME
      value: elastic
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: system-passwords
          key: datastore-password
  labels:
    app: assemblyline
    section: core
    component: datastore
  esJavaOpts: '-Xms6g -Xmx6g'
  esConfig:
    elasticsearch.yml: |
      logger.level=WARN
  resources:
    requests:
      cpu: 1
      memory: 12Gi
    limits:
      cpu: 6
      memory: 12Gi
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: default
    resources:
      requests:
        storage: 500Gi
  priorityClassName: 'al-infra'


logging-datastore:
  clusterName: "logging-datastore"
  replicas: 1
  extraEnvs:
  - name: ELASTIC_USERNAME
    value: elastic
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: system-passwords
        key: logging-password
  labels:
    app: assemblyline
    section: core
    component: logging-datastore
  esJavaOpts: '-Xms6g -Xmx6g'
  esConfig:
    elasticsearch.yml: |
      logger.level=WARN
  resources:
    requests:
      cpu: 1
      memory: 12Gi
    limits:
      cpu: 6
      memory: 12Gi
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: default
    resources:
      requests:
        storage: 500Gi
  priorityClassName: 'al-infra'

