# Default values for assemblyline.

coreVersion: '4.0.0.dev46'
uiVersion:   '4.0.0.dev48'
sapiVersion:   '4.0.0.dev34'

storage:
  filestore: default
  datastore: default
  redis: default

domain: localhost
maxBodySize: 100M

tls:
  secretName: ''

autoInstallServices:
  - apkaye
  - cleaver
  - espresso
  - extract
  - frankenstrings
  - iparse
  - metapeek
  - pdfid
  - peepdf
  - unpacker
  - characterize

serviceNamespace: null  # Will be {{ .Release.Name }}-services if not defined