# Default values for assemblyline.

coreVersion: '4.0.0.dev12'
uiVersion:   '4.0.0.dev23'
sapiVersion:   '4.0.0.dev6'

storage:
  filestore: default
  datastore: default
  redis: default

net:
  domain: localhost
  maxBodySize: 100M

tls:
  secretName: ''

autoInstallServices:
  - apkaye
  - cleaver
  - espresso
  - extract
  - frankenstrings
  - iparse
  - metapeek
  - pdfid
  - peepdf
  - unpacker
